import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Simple Omelette Recipe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/assets/images/favicon-32x32.png" sizes="any" />
      <body className={`bg-Eggshell`}>
        {children}
        <div className="attribution hidden sm:block">
          Challenge by <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">Frontend Mentor</a>.
          Coded by <a href="https://github.com/ahtesham-clcbws" target="_blank">Ahtesham</a>.
        </div>
      </body>
    </html>
  );
}
